name: Verify Formatting

on:
  - pull_request
  - push

jobs:
  verify-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up V
        uses: vlang/setup-v@v1.1
        with:
          check-latest: true

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify That The Code Is Formatted
        run: v fmt -verify .
